### PR TITLE
use external smart_fact_crawler package 

### PR DESCRIPTION
**Pull request by dneise**

### CODE REVIEW

**Comment by MaxNoe** [comment]
My Problem with this is, that this breaks `pip` installability.

But i think i can fix this if smartfact published releases. @relleums 
This would mean creating a git tag and pushing it like this:

```
git tag v0.3.0
git push --tags
```

**Comment by dneise** [comment]
He has other stuff to do atm. But I will create the tags in a moment.

**Comment by MaxNoe** [comment]
Like I said. I do not like the other solution to much. 

I just had a look around. And for example scikit learn also includes other packages as code. For example `joblib` and `six`.

**Comment by MaxNoe** [comment]
I see it like this: updating the `crawler` manually  is a minor inconvenience for us, but not able to install the shift helper via a simple `pip install` is a major inconvenience for our users.

**Comment by dneise** [comment]
I agree, the stuff should be pip installable.

But I cannot believe its smart to copy external dependencies into your project, because pip cannot handle the installation at the moment.

smart_fact_crawler is pip installable. 
shifthelper is also pip installable.

the problem is only pip is not capable of understanding how to resolve "smart_fact_crawler" as a dependency for shifthelper. But this cannot lead us to the decision to include any external dependency into the project. Can it?

**Comment by MaxNoe** [comment]
Should we merge this now?

**Comment by dneise** [comment]
erm ...

**Comment by dneise** [comment]
I'd say yes :-D

**Pull request merged**
