### PR TITLE
Call

### PR DESCRIPTION
**Pull request by MaxNoe**
* Add executable `fact_call` which just calls the given number via the fact twilio account

### CODE REVIEW

**Comment by dneise** [comment]
Ah ... I overlooked this PR as it was made on a day, when github had some issues.

I think it can be merged. do we need to increase the total shifthelper version number? I don't think so, since this PR doesn't modify any existing feature.

**Comment by dneise** [comment]
Just a comment, with the [Message Twimlet](https://www.twilio.com/labs/twimlets/message) one can include a feature like

    fact_call +4123456789 FACT Flare Alert 1959 at 1 crab unit with 4.1 sigma.

easily.

**Comment by MaxNoe** [comment]
Wow, that's cool.

**Comment by dneise** [comment]
yep, but I got no time at the moment to do it .. and the feature is not really needed.
What do you say? merge?

**Comment by dneise** [comment]
how does the call look?
Does one need to put the message in `"` or so?

**Comment by MaxNoe** [comment]
Yes.
`fact_call +12456 "Hello, World!"`

**Comment by dneise** [comment]
perfect ..

**Pull request merged**
