### PR TITLE
Fixqla

### LINKED ISSUE #1: QLA: is binning identical to DDs QLA binning?
Originally reported by: **Dominik Neise (Bitbucket: [dneise](http://bitbucket.org/dneise), GitHub: [dneise](http://github.com/dneise))**

---

Told Gareth about the recent new feature of looking into the QLA. He likes it, but immediately asked, if the code you wrote, and the stuff DD makes are equivalent?

Could you explain this a bit, if you have time?

---
- Bitbucket: https://bitbucket.org/dneise/fact_shift_helper/issue/1

### PR DESCRIPTION
**Pull request by MaxNoe**
This contains to fixes:

* qla binning is now identical to Daniela's, this fixes #1 and #61 
* the qla_bot has better connection error handling

### CODE REVIEW

**Comment by dneise** [comment]
looks good. I'll try it out tonight and merge tomorrow?

**Comment by MaxNoe** [comment]
Sounds good to me.

**Comment by MaxNoe** [comment]
I compared older qla plots with mine, they also match:


2014-06-23:
qls_20140623

qla_2016-02-03_14-41-20

**Comment by MaxNoe** [comment]
I just saw, that my error bars were a bit larger than Danielas, i think I found te error in my calculation. The NumBGEvents in the database is already divided by the number of off-positions, this is the result now:
qla_2016-02-04_14-37-58

**Comment by dneise** [comment]
Looks good to me

**Pull request merged**
